### ISSUE TITLE
Added RIGHT JOIN, changed default behaviour of JOIN

### ISSUE THREAD

**Issue by oshamin** [dsferruzza/simpleSqlParser#7]
Added RIGHT JOIN.
Changed default behaviour of JOIN from LEFT JOIN to INNER JOIN.

https://github.com/oshamin/simpleSqlParser/commit/50bf0bd4b3b50d71c1679f38a5aada163d37f65e

**Comment by dsferruzza** [comment]
Hi!

Thanks for your contribution!
The changes you made totally make sense, but there are some minor issues with your implementation:
- you should have done 2 commits because there are 2 different changes
- you have used spaces for indentation whereas the rest of the project uses tabs

If you fix these issues and make a pull request, I'll merge it!
Is this OK for you?
_You seem new to GitHub, so tell me if you need help._

Also, I'm starting to think about rewriting the whole project.
Feel free to comment #6 !
